# Site settings

# host: 192.168.1.66

title: "Wishlist"
description: "I'm John Peart. These are things I might buy or that you might like to buy for me."

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wishlist.johnpe.art"
author: "John Peart"

# Images and assets
image-path: "/assets/images"
css-path: "/assets/styles"
js-path: "/assets/scripts"

social-media-image: "/assets/images/site/social-media.png"

theme-colour: "#007aff"

favicon: "/favicon.ico"
favicon-svg: "/assets/images/site/favicon.svg"
favicon-pinned-svg: "/assets/images/site/favicon-pinned-svg.svg"
favicon-large-png: "/assets/images/site/favicon-large-png.png"

# Social settings
twitter-url: "https://twitter.com/johnpeart" # Twitter handle i.e. joebloggs
twitter-handle: "johnpeart" # Twitter handle i.e. joebloggs

linkedin-url:  "https://www.linkedin.com/in/jrpeart"
linkedin-handle:  "jrpeart"

flickr-url:  "https://www.flickr.com/photos/johnpeart"
flickr-handle:  "johnpeart"

instagram-url:  "https://www.instagram.com/johnpeart"
instagram-handle:  "johnpeart"

github-url:  "https://github.com/johnpeart"
github-handle:  "johnpeart"

# Google settings
google-site-verification: "DaqGCZ6cZIqm7q_nVSnOzjJmFFjbRfW2X7FDzpQDQZk"
google-analytics: "UA-27553664-1" # GA ID code

# Site header

header: false

# Plugins and build settings

permalink: pretty
markdown: kramdown
future: false
sass:
    sass_dir: _sass

remote_theme: johnpeart/jekyll-theme

# rebuild: "2020-12-03 00:50"