######################
# Site configuration #
######################
title: "Wishlist"
description: "I'm John Peart. These are things I might buy or that you might like to buy for me."
author: "John Peart"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wishlist.johnpe.art"

####################
# Feature settings #
####################
menu-subdomain: true
menu-header: false
menu-footer: true
analytics: true

###############
# Asset paths #
###############
image-path: "/assets/images"
css-path: "/assets/styles"
js-path: "/assets/scripts"
social-media-image: "/assets/images/site/social-media.png"
favicon: "/favicon.ico"
favicon-svg: "/assets/images/site/favicon.svg"
favicon-pinned-svg: "/assets/images/site/favicon-pinned-svg.svg"
favicon-large-png: "/assets/images/site/favicon-large-png.png"
theme-colour: "#009fe3"

#######################
# <link rel="me" ...> #
#######################
# Twitter
twitter-url: "https://twitter.com/johnpeart" # Twitter handle i.e. joebloggs
twitter-handle: "johnpeart" # Twitter handle i.e. joebloggs
# Mastodon
mastodon-url: "https://mastodon.social/@johnpeart"
mastodon-handle: "johnpeart@mastodon.social"
# Github
github-url:  "https://github.com/johnpeart"
github-handle:  "johnpeart"

##################
# Build settings #
##################
remote_theme: johnpeart/theme
permalink: pretty
markdown: kramdown
future: false
highlighter: rouge
sass:
  sass_dir: _sass

# plugins:
# - jekyll-sitemap
# - jekyll-feed
# - jekyll-redirect-from